# Generated by Django 3.1.7 on 2021-03-03 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.SmallIntegerField(choices=[(0, 'sign up'), (1, 'create post'), (2, 'create comment')], unique=True)),
                ('point', models.SmallIntegerField()),
                ('valid_period', models.SmallIntegerField(verbose_name='유효 기간(일)')),
            ],
        ),
        migrations.CreateModel(
            name='PointIssued',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.SmallIntegerField(choices=[(0, 'sign up'), (1, 'create post'), (2, 'create comment')])),
                ('point', models.PositiveSmallIntegerField()),
                ('remained_point', models.PositiveSmallIntegerField()),
                ('expire_at', models.DateTimeField(verbose_name='만료일')),
                ('created_at', models.DateTimeField(verbose_name='획득일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointConsumed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.SmallIntegerField(choices=[(0, 'sign up'), (1, 'create post'), (2, 'create comment')])),
                ('point', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
