# Generated by Django 3.1.7 on 2021-03-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointdefinition',
            name='point',
            field=models.SmallIntegerField(help_text='포인트를 소모해야하는 액션은 음수를 입력해주세요.'),
        ),
        migrations.AlterField(
            model_name='pointdefinition',
            name='valid_period',
            field=models.SmallIntegerField(default=0, help_text='포인트를 소모해야하는 액션은 비워도되는 항목입니다.', verbose_name='유효 기간(일)'),
        ),
    ]
