# Generated by Django 3.1.7 on 2021-03-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_auto_20210306_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointdefinition',
            name='valid_period',
            field=models.SmallIntegerField(help_text='포인트를 소모해야하는 액션은 0을 입력해주세요.', verbose_name='유효 기간(일)'),
        ),
    ]
